
GRANT SELECT, INSERT ON SEGMERCADO TO user_app;

CREATE PUBLIC SYNONYM SEGMERCADO FOR user_dev.SEGMERCADO;

GRANT EXECUTE ON EXCEPTION_PAC TO PUBLIC;

CREATE PUBLIC SYNONYM EXCEPTION_PAC FOR user_dev.EXCEPTION_PAC;