
CREATE SMALLFILE TABLESPACE NEWTBS3
DATAFILE 'C:\app\oracle12c\oradata\NEWTBS3_01.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1M MAXSIZE 10M;

ALTER TABLESPACE NEWTBS3 RENAME TO NEWTBS4;

ALTER TABLESPACE NEWTBS4 OFFLINE;

ALTER DATABASE RENAME FILE 'C:\app\oracle12c\oradata\NEWTBS3_01.dbf' TO 'C:\app\oracle12c\oradata\NEWTBS4_01.dbf';

ALTER TABLESPACE NEWTBS4 ONLINE;

CREATE TABLE TEST_TAB (C1 DATE) TABLESPACE NEWTBS4;

ALTER TABLESPACE NEWTBS4 READ ONLY;

INSERT INTO TEST_TAB VALUES (SYSDATE);

ALTER TABLESPACE NEWTBS4 READ WRITE;

INSERT INTO TEST_TAB VALUES (SYSDATE);

DROP TABLESPACE NEWTBS4;

DROP TABLESPACE NEWTBS4 INCLUDING CONTENTS AND DATAFILES;


