
CREATE SMALLFILE TABLESPACE NEWTBS1
DATAFILE 'C:\app\oracle12c\oradata\NEWTBS1_01.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1M MAXSIZE 10M;

CREATE TABLE NEWTAB1 (C1 DATE) TABLESPACE NEWTBS1;

CREATE TABLE NEWTAB2 TABLESPACE NEWTBS1 AS SELECT * FROM ALL_OBJECTS;

ALTER TABLESPACE NEWTBS1
ADD DATAFILE 'C:\app\oracle12c\oradata\NEWTBS1_02.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1M MAXSIZE 10M;

CREATE TABLE NEWTAB2 TABLESPACE NEWTBS1 AS SELECT * FROM ALL_OBJECTS;

CREATE SMALLFILE TABLESPACE NEWTBS2
DATAFILE 'C:\app\oracle12c\oradata\NEWTBS2_01.dbf'
SIZE 1M AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE TABLE NEWTAB3 (C1 DATE) TABLESPACE NEWTBS2;

CREATE TABLE NEWTAB4 TABLESPACE NEWTBS2 AS SELECT * FROM ALL_OBJECTS;

ALTER TABLESPACE NEWTBS1 OFFLINE;

SELECT * FROM NEWTAB2;

ALTER TABLESPACE NEWTBS1 ONLINE;

SELECT * FROM NEWTAB2;

DROP TABLESPACE NEWTBS2;

DROP TABLE NEWTAB4;

DROP TABLE NEWTAB3;

DROP TABLESPACE NEWTBS2;


DROP TABLE NEWTAB2;

DROP TABLE NEWTAB1;

DROP TABLESPACE NEWTBS1;


