
EXECUTE CLIENTE_PAC.INCLUIR_CLIENTE(15, 'INCLUIR CLIENTE COM 5 PARAMETROS', '99999',2, 90000);

SELECT * FROM CLIENTE;

EXECUTE CLIENTE_PAC.INCLUIR_CLIENTE(16, 'INCLUIR CLIENTE COM 3 PARAMETROS', 2);